### ISSUE TITLE
HWYLA/WAILA formatting issues

### ISSUE THREAD

**Issue by IronPiston** [Lordmau5/FFS#22]
**FancyFluidStorage Version**:
1.12.2-2.2.3
**MinecraftForge Version**:
1.12.2
**Client or Server?**:
- [x] Client
- [ ] Server

**What happens / happened?**:
Note that all this occurs with HWYLA set to display fluid in tanks under "Capability"

Looking at any block comprising a tank, it displays the type of fluid and the amount. This seems to be the built in WAILA compatability from FFS. Looking at the tank valve, it will list both HWYLA's built in fluid display and FFS's WAILA integration.

If I were to disable HWYLA's built in fluid display, it would affect liquid display for tanks from other mods, but leaving it on leads to redundancy when looking at the valve.

Maybe this could be fixed by providing a config or a button under HWYLA to display fluid amount only when looking at tank blocks instead of the valve, or make the entire tank visible to HWYLA and let it handle displaying fluid capacity. Or just include an option to disable FFS WAILA integration all together? Basically, I'd prefer to leave on HWYLA's default tank capacity setting and avoid redundancy.

This is more nitpicky, but the way FFS displays fluid levels could also be changed to display similar to how HWYLA does it natively, displaying the liquid followed by the amount as opposed to listing the liquid type and amount on separate lines. For example:

Liquid Blue Slime: 15000 mB / 40000 mB
vs.
Fluid: Liquid Blue Slime
Amount: 15000 mB/40000 mB

https://imgur.com/a/1PgF3Yz

**How can we reproduce it?**:
Enable HWYLA's "Show tank data" under "Capability"

**Comment by Lordmau5** [comment]
Hey there - for whatever reason GitHub has made me unwatch this repository and I never got any notification about the new issues, so I'm really sorry that I respond to this so damn late.

Due to the way that FFS tanks are handled (keep the same block in-world, and use a hook on them, effectively), it's a bit difficult to use the exact same capability HWYLA offers.

I can look into potentially using *their* method to include it in the tooltip, but I'm not 100% sure if it's gonna be possible
