### ISSUE TITLE
Volume-per-block-type

### ISSUE THREAD

**Issue by pyure** [Lordmau5/FFS#25]
Given the whitelist you've provided in #23, it would be very powerful if that could be extended with an integer or float (percentage) which would indicate how much that type of block affects the volume of the tank.

I haven't the faintest notion how I'd break this down mathematically: possibly just by summing up the volume-value all the frame blocks and calculating the total volume from that (rather than by internal air blocks).

It would really only have meaning while in Whitelist mode.
Possible example: 
`minecraft:redstone_block 500 // Every frame block of redstone contributes 500 to total volume`

**Comment by Lordmau5** [comment]
The current system is calculating the volume / capacity based on the amount of air blocks in the tank (like pretty much every other tank mod).

I know that with RailCraft you can have either an Iron Tank or a Steel Tank, which has double the capacity of the Iron Tank.

The problem with the system that I have in FFS is that I'm only able to figure out the walls of the tank, not the actual outer frame (think 5x5x5 tank that has 3x3 walls - I wouldn't be able to know about the blocks on the "outer frame"), so that's one downside to this.

In theory this should be doable, but I need to look into how to best handle it, really

**Comment by pyure** [comment]
Woops I miscommunicated.  I shouldn't have said "frame", particularly since I noticed that FFS tanks only seem to need the walls adjacent to the internal air blocks.

I was referring to the walls themselves.  Specifically: A 3x3x3 tank (cube) has 27 internal air blocks, and if I'm not mistaken requires 54 wall blocks (53 plus a valve.)

I'm wondering if the total volume could be calculated based (primarily?) on the 53 wall blocks rather than the 27 internal blocks.  For most users who are inclined to build their tanks from whatever material amuses them this would just default to a standard volume-per-block value, but for us we'd do crazy things like use space-age materials to make super-high-volume tanks.

And if all of the above is absurd, a poor-mans-substitute is multiple tiers of valves, with the volume of the tank using either the "first" valve or the "best" valve as a multiplier.

**Comment by Lordmau5** [comment]
Do you have Discord? If so, do you mind adding me so we can talk about this a bit more in detail over there?

My ID is `Lordmau5#0001` - GitHub, same as with Twitter, is a nice place to talk this through, but considering I'm pretty much 24/7 available on Discord it's just a better place to do that imo.

I'm still going to be updating this issue once we've come to an interesting way to handle it, of course

**Comment by pyure** [comment]
Certainly!
