### ISSUE TITLE
3 suggestions

### ISSUE THREAD

**Issue by Tenchu98** [Lordmau5/FFS#7]
1) allowing a double walled hollow cube for the tank shape. I was thinking it would be nice to make a lava tank that is actually the walls of a room.

2) have a tank emit light to prevent mobs from spawning inside, or have fluids damage any mobs that spawn there.

3) allow pulling a valve that has fluid, but it loses any fluid it has in it unless you use a T.I.T. 
         I tried to empty the valve when it glitches, but was not able to break it without making the T.I.T

**Comment by Lordmau5** [comment]
Bit late to respond to this, but here goes:

1. You're actually able to do that by just... making a double-walled hollow cube / wall, seeing as FFS doesn't restrict you by cuboid tank shapes. You can make any shape you want, as long as it contains less than 2197 (or the configured max. amount) of air blocks.
https://i.imgur.com/caDIdEN.gifv

2. That's fixed in the latest build (v2.2.3 as of this reply)

3. The T.I.T. is now only needed in the off-hand when you want to interact with a TileEntity that is part of a tank
